version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    expose:
      - "4321"  # Expose to the internal network, not to the host machine

  api:
    build:
      context: ./api
    working_dir: /app
    expose:
      - "8080"  # Expose to the internal network, not to the host machine

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config file
    ports:
      - "80:80"  # Expose Nginx on port 80 to the host
    depends_on:
      - frontend
      # - api
    networks:
      - default  # Ensure Nginx can communicate with the other services

