version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    expose:
      - "4321"

  api:
    build:
      context: ./api
    working_dir: /app
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.common.conf:/etc/nginx/nginx.common.conf:ro
      - ./nginx/nginx.docker.conf:/etc/nginx/nginx.conf:ro  # Use Docker-specific config
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api

