services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro  # Mount the config file
    ports:
      - "80:80"  # Expose Nginx on port 80 to the host
    network_mode: "host"  # Use host network for Nginx
